export const componentTokens = {
  Button: {
    fontWeight: 500,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    borderRadius: 8,
    primaryShadow: '0 1px 3px rgba(0, 57, 115, 0.20)',
    dangerShadow: '0 1px 3px rgba(230, 38, 38, 0.25)',
    defaultBorderColor: '#D5DCE5',
    defaultBg: '#FFFFFF',
    paddingInline: 20,
    paddingInlineLG: 28,
  },
  Input: {
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    borderRadius: 8,
    activeBorderColor: '#00BBDD',
    hoverBorderColor: '#80E0F0',
    activeShadow: '0 0 0 3px rgba(0, 187, 221, 0.12)',
    paddingInline: 14,
  },
  Select: {
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    borderRadius: 8,
    optionSelectedBg: '#E8F0FA',
    optionActiveBg: '#F2F7FC',
    selectorBg: '#FFFFFF',
  },
  DatePicker: {
    controlHeight: 40,
    borderRadius: 8,
    activeBorderColor: '#00BBDD',
    hoverBorderColor: '#80E0F0',
    activeShadow: '0 0 0 3px rgba(0, 187, 221, 0.12)',
  },
  Table: {
    headerBg: '#F0F3F7',
    headerColor: '#3D5068',
    headerSortActiveBg: '#E8EDF2',
    headerSortHoverBg: '#E8EDF2',
    headerFilterHoverBg: '#E8EDF2',
    rowHoverBg: '#F5F8FB',
    rowSelectedBg: '#E8F0FA',
    rowSelectedHoverBg: '#D6E6F5',
    borderColor: '#E8EDF2',
    headerBorderRadius: 8,
    cellPaddingBlock: 14,
    cellPaddingInline: 16,
    cellFontSize: 14,
    headerSplitColor: 'transparent',
  },
  Card: {
    borderRadiusLG: 12,
    boxShadow:
      '0 1px 3px rgba(0, 25, 51, 0.05), 0 0 0 1px rgba(0, 25, 51, 0.03)',
    headerFontSize: 15,
    paddingLG: 24,
  },
  Modal: {
    borderRadiusLG: 16,
    titleFontSize: 18,
    paddingContentHorizontalLG: 28,
    headerBg: '#FFFFFF',
    contentBg: '#FFFFFF',
    footerBg: '#FFFFFF',
  },
  Drawer: {
    borderRadiusLG: 0,
    paddingLG: 28,
  },
  Menu: {
    darkItemBg: 'transparent',
    darkSubMenuItemBg: 'transparent',
    darkItemSelectedBg: 'rgba(0, 187, 221, 0.12)',
    darkItemHoverBg: 'rgba(255, 255, 255, 0.04)',
    darkItemColor: 'rgba(255, 255, 255, 0.45)',
    darkItemSelectedColor: '#FFFFFF',
    darkItemHoverColor: 'rgba(255, 255, 255, 0.85)',
    itemBorderRadius: 8,
    itemMarginBlock: 2,
    itemMarginInline: 8,
    itemPaddingInline: 14,
    itemHeight: 40,
    iconSize: 18,
    collapsedIconSize: 18,
  },
  Layout: {
    siderBg: '#001224',
    headerBg: '#FFFFFF',
    bodyBg: '#F0F3F7',
    headerHeight: 68,
    headerPadding: '0 32px',
  },
  Tag: {
    borderRadiusSM: 6,
    defaultBg: '#EDF0F4',
    defaultColor: '#3D5068',
  },
  Badge: {
    dotSize: 8,
  },
  Alert: {
    borderRadiusLG: 10,
  },
  Notification: {
    borderRadiusLG: 12,
  },
  Breadcrumb: {
    fontSize: 13,
    separatorMarginInline: 8,
    separatorColor: '#B8C4D0',
    itemColor: '#8494A7',
    lastItemColor: '#3D5068',
  },
  Tabs: {
    inkBarColor: '#003973',
    itemSelectedColor: '#0D1B2A',
    itemHoverColor: '#3D5068',
    itemColor: '#8494A7',
    titleFontSize: 14,
  },
  Pagination: {
    itemActiveBg: '#003973',
    itemBg: '#FFFFFF',
    borderRadius: 8,
    controlHeight: 36,
  },
  Tooltip: {
    borderRadius: 8,
    colorBgSpotlight: '#001224',
  },
  Popover: {
    borderRadiusLG: 12,
  },
  Dropdown: {
    borderRadiusLG: 12,
    paddingBlock: 6,
    controlItemBgActive: '#E8F0FA',
    controlItemBgHover: '#F5F8FB',
  },
  Spin: {
    colorPrimary: '#00BBDD',
  },
  Switch: {
    colorPrimary: '#003973',
    colorPrimaryHover: '#004A94',
    handleSize: 18,
    trackHeight: 24,
    trackMinWidth: 44,
  },
  Checkbox: {
    borderRadiusSM: 4,
    colorPrimary: '#003973',
  },
  Radio: {
    colorPrimary: '#003973',
  },
  Segmented: {
    borderRadius: 8,
    borderRadiusSM: 6,
    itemSelectedBg: '#FFFFFF',
    trackBg: '#E8EDF2',
  },
}
